# Generated by Django 4.1.1 on 2022-10-13 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_is_active_alter_listing_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="image",),
        migrations.RemoveField(model_name="listing", name="url",),
        migrations.AddField(
            model_name="listing",
            name="image_url",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="watchlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
