# Generated by Django 4.1.1 on 2022-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_listing_image_remove_listing_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="watchlist",),
    ]
