# Generated by Django 4.1.1 on 2022-10-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_comment_listing_alter_comment_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="bid", name="listing",),
        migrations.AlterField(
            model_name="listing",
            name="start_bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.bid"
            ),
        ),
    ]
