# Generated by Django 4.1.1 on 2022-10-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_remove_bid_listing_alter_listing_start_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="start_bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userbids",
                to="auctions.bid",
            ),
        ),
    ]
